services:
  blacklist:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=postgres
      - RDS_HOST=blacklistdb
      - RDS_PORT=5432
      - RDS_DB_NAME=blacklist
    networks:
        - blacklist_net
    depends_on:
      blacklistdb:
        condition: service_healthy

  blacklistdb:
    image: postgres:15
    networks:
        - blacklist_net
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=blacklist
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  blacklist_net:
